/msys64/usr/bin/bash -lc 'pacman -Syu --noconfirm'
/msys64/usr/bin/bash -lc 'pacman -Syu --noconfirm'
/msys64/usr/bin/bash -lc 'pacman -Syu --noconfirm'
/msys64/usr/bin/bash -lc 'pacman -Syu --noconfirm'
/msys64/usr/bin/bash -lc 'pacman -Syu --noconfirm'
